# Framashare Makefile
all: install

# Start the development environment (Frontend + Backend concurrently)
dev:
	npm run dev

# Install all dependencies for the workspace
install:
	npm install

# Build production artifacts (Frontend Vue + Backend Fastify)
build:
	npm run build

# Start Docker Compose (PostgreSQL, Proxy, Backend)
db-up:
	docker compose up -d

# Stop Docker Compose
db-down:
	docker compose down

# Run Prisma Migrations and generate client
db-migrate:
	cd back && npx prisma migrate dev && npx prisma generate

# Colorcitos down ñeheheheh
# ⣿⣿⣿⠟⠛⠛⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⢋⣩⣉⢻⣿⡇
# ⣿⣿⣿⠀⣿⣶⣕⣈⠹⠿⠿⠿⠿⠟⠛⣛⢋⣰⠣⣿⣿⠀⣿⣿
# ⣿⣿⣿⡀⣿⣿⣿⣧⢻⣿⣶⣷⣿⣿⣿⣿⣿⣿⠿⠶⡝⠀⣿⣿
# ⣿⣿⣿⣷⠘⣿⣿⣿⢏⣿⣿⣋⣀⣈⣻⣿⣿⣷⣤⣤⣿⡐⢿⣿
# ⣿⣿⣿⣿⣆⢩⣝⣫⣾⣿⣿⣿⣿⡟⠿⠿⠦⠀⠸⠿⣻⣿⡄⢻
# ⣿⣿⣿⣿⣿⡄⢻⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣾⣿⣿⣿⣿⠇⣼
# ⣿⣿⣿⣿⣿⣿⡄⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⣰⣿
# ⣿⣿⣿⣿⣿⣿⠇⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢀⣿⣿
# ⣿⣿⣿⣿⣿⠏⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢸⣿⣿
# ⣿⣿⣿⣿⠟⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⣿⣿
# ⣿⣿⣿⠋⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⣿⡇
# ⣿⣿⠋⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⡇
# ⣿⠏⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡯⢸⡇
#Fabricio was here, Fabricio is here, Fabricio will be here.

CYAN  := \033[36m
GREEN := \033[32m
YELLOW:= \033[33m
RED   := \033[31m
RESET := \033[0m

# Clean generated files (dist, prisma client)
clean:
	@printf "$(CYAN)Cleaning autogenerated files (dist, build, prisma) 🧹 "
	@for i in 1 2 3; do printf "."; sleep 0.2; done; printf "$(RESET)\n"
	@rm -rf frontend/dist
	@rm -rf back/dist
	@rm -rf back/prisma/generated
	@printf "$(GREEN)Partial clean completed :D ✨$(RESET)\n"

# Full clean (clean + remove all node_modules and locks)
fclean: clean
	@printf "$(RED)Deep clean: removing dependencies (node_modules)...$(RESET)\n"
	@printf "$(YELLOW)Starting with frontend 🧹 "
	@for i in 1 2 3; do printf "."; sleep 0.2; done; printf "$(RESET)\n"
	@rm -rf node_modules package-lock.json
	@rm -rf frontend/node_modules frontend/package-lock.json
	@printf "$(GREEN)Frontend clean completed :D ✨$(RESET)\n"
	
	@printf "$(YELLOW)Starting with backend 🧹 "
	@for i in 1 2 3; do printf "."; sleep 0.2; done; printf "$(RESET)\n"
	@rm -rf back/node_modules back/package-lock.json
	@printf "$(GREEN)Total clean completed :D ✨$(RESET)\n"

# Re-install and setup everything from scratch
re: fclean install



.PHONY: all dev build install clean fclean re db-up db-down db-migrate
