import { test, expect } from '@playwright/test';
import { seedState, STORAGE_KEY } from '../src/services/store';
import { mkdirSync } from 'node:fs';
const shots='docs/verification/screenshots';
mkdirSync(shots,{recursive:true});
test.beforeEach(async({page})=>{
  const seed=seedState();seed.currentUserId='admin';
  await page.addInitScript(({key,seed})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(seed))},{key:STORAGE_KEY,seed});
});
for(const width of [1440,390,320]){
 test(`admin review and settings work at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:900});
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/admin/reports');await page.waitForLoadState('networkidle');
  await expect(page.getByRole('heading',{name:'Reports',exact:true})).toBeVisible();
  await expect(page.getByRole('link',{name:'Review report'})).toHaveCount(1);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  if(width!==320)await page.screenshot({path:`${shots}/admin-reports-${width===1440?'desktop':'mobile'}.png`,fullPage:true});
  await page.getByRole('link',{name:'Review report'}).click();
  await expect(page.getByRole('heading',{name:'Report details',exact:true})).toBeVisible();
  if(width!==320)await page.screenshot({path:`${shots}/admin-report-details-${width===1440?'desktop':'mobile'}.png`,fullPage:true});
  await page.getByRole('button',{name:'Remove publication',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Remove publication?'})).toBeVisible();
  if(width!==320)await page.screenshot({path:`${shots}/admin-removal-dialog-${width===1440?'desktop':'mobile'}.png`,fullPage:false});
  await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:'Dismiss report',exact:true}).click();
  await expect(page.locator('main').getByText('Resolved',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Accounts',exact:true}).click();
  await page.getByRole('link',{name:'View account'}).first().click();
  await page.getByLabel('Storage limit (MB)').fill('1');
  await page.getByRole('button',{name:'Save storage limit'}).click();
  await expect(page.getByText('This account is above its limit. New uploads are blocked until space is freed.')).toBeVisible();
  if(width!==320)await page.screenshot({path:`${shots}/admin-account-quota-${width===1440?'desktop':'mobile'}.png`,fullPage:true});
  await page.getByRole('link',{name:'Instance settings',exact:true}).click();
  await page.getByLabel('Maximum PDF or EPUB size (MB)').fill('120');
  await page.getByRole('button',{name:'Save instance settings'}).click();
  await expect(page.getByText('Instance settings saved',{exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  if(width!==320)await page.screenshot({path:`${shots}/admin-settings-${width===1440?'desktop':'mobile'}.png`,fullPage:true});
  await page.getByLabel('30 days',{exact:true}).uncheck();
  await page.getByRole('button',{name:'Save instance settings'}).click();
  await expect(page.getByText('Instance settings saved',{exact:true})).toBeVisible();
  expect(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).documents.find((d:{id:string})=>d.id==='anon1').deleteAt,STORAGE_KEY)).toBe(seedState().documents.find(d=>d.id==='anon1')!.deleteAt);
  expect(errors).toEqual([]);
 });
}
test('administrative removal resolves reports and invalidates recipient links',async({page})=>{
 await page.goto('/admin/reports/report1');await page.waitForLoadState('networkidle');
 await page.getByRole('button',{name:'Remove publication',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Remove publication',exact:true}).click();
 await expect(page.getByText('Publication removed',{exact:true}).first()).toBeVisible();
 await expect(page.locator('main').getByText('Resolved',{exact:true})).toBeVisible();
 const snapshot=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),STORAGE_KEY);
 expect(snapshot.documents.find((d:{id:string})=>d.id==='doc1').status).toBe('removed');
 expect(snapshot.reports.find((r:{id:string})=>r.id==='report1').status).toBe('resolved');
 await page.goto('/share/workshop');
 await expect(page.locator('main')).not.toContainText('Community workshop handbook');
 await expect(page.locator('main')).toContainText(/removed|unavailable/i);
});
test('settings validate retention and preserve values on simulated connection failure',async({page})=>{
 await page.goto('/overview');await page.getByRole('button',{name:'Fail next operation'}).click();
 await page.getByRole('button',{name:'Instance settings',exact:true}).click();
 await page.getByLabel('Maximum PDF or EPUB size (MB)').fill('130');
 await page.getByRole('button',{name:'Save instance settings'}).click();
 await expect(page.getByRole('alert')).toContainText('Connection interrupted');
 expect(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).settings.fileMB,STORAGE_KEY)).toBe(100);
 await page.getByRole('button',{name:'Save instance settings'}).click();
 await expect(page.getByText('Instance settings saved',{exact:true})).toBeVisible();
 for(const name of ['1 day','7 days','30 days'])await page.getByLabel(name,{exact:true}).uncheck();
 await page.getByRole('button',{name:'Save instance settings'}).click();
 await expect(page.getByRole('alert')).toContainText('Allow at least one anonymous retention period.');
 expect(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).settings.retention,STORAGE_KEY)).toEqual([1,7,30]);
 await page.getByRole('button',{name:'Discard changes'}).click();
 await expect(page.getByLabel('7 days',{exact:true})).toBeChecked();
});
