import { test, expect } from '@playwright/test';
import { PDFDocument, StandardFonts } from 'pdf-lib';

test('account, durable PDF and independent client without local owner state', async ({ browser, baseURL }) => {
  const email = `browser-${crypto.randomUUID()}@example.com`;
  const password = 'correct-password';
  const author = await browser.newContext({ extraHTTPHeaders: { 'X-Forwarded-For': '192.0.2.10' } });
  const second = await browser.newContext({ extraHTTPHeaders: { 'X-Forwarded-For': '192.0.2.11' } });
  const guest = await browser.newContext();
  const page = await author.newPage();
  try {
    await page.goto(baseURL + '/sign-up');
    await page.getByLabel('Your name').fill('PDF Author');
    await page.getByLabel('Email address').fill(email);
    await page.getByLabel('Password', { exact: true }).fill(password);
    await page.getByLabel('Password', { exact: true }).press('Enter');
    await expect(page).toHaveURL(/\/app\/library$/);
    const pdf = await PDFDocument.create();
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    pdf.addPage().drawText('Persistent private PDF', { font });
    await page.goto(baseURL + '/upload');
    await page.locator('input[type=file]').setInputFiles({ name: 'persistent.pdf', mimeType: 'application/pdf', buffer: Buffer.from(await pdf.save()) });
    await page.getByLabel('Title', { exact: true }).fill('Persistent handbook');
    await page.getByLabel(/^Description/).fill('Remember these details');
    await expect(page.getByLabel('Usage rights')).toHaveValue('unspecified');
    await expect(page.getByLabel('Author credit', { exact: true })).toHaveCount(0);
    await page.getByLabel('Usage rights').selectOption('CC-BY-4.0');
    await expect(page.getByLabel('Author credit', { exact: true })).toHaveValue('PDF Author');
    await page.getByLabel('Author credit', { exact: true }).fill('Handbook collective');
    await page.getByRole('button', { name: 'Upload document', exact: true }).click();
    await expect(page).toHaveURL(/\/upload\/complete\//);
    const id = page.url().split('/').pop()!;
    const ownerResponse = await author.request.get(baseURL + '/api/files/' + id);
    expect(ownerResponse.status()).toBe(200);
    expect((await ownerResponse.body()).subarray(0, 5).toString()).toBe('%PDF-');
    expect((await guest.request.get(baseURL + '/api/files/' + id)).status()).toBe(401);
    await page.goto(baseURL + '/app/documents/' + id + '/read');
    await expect(page.locator('canvas').first()).toBeVisible();
    await expect(page.getByRole('link', { name: 'CC BY 4.0', exact: true })).toHaveAttribute('href', 'https://creativecommons.org/licenses/by/4.0/');
    await expect(page.getByText('Author: Handbook collective', { exact: false })).toBeVisible();
    await expect(page.getByText('File unavailable in this browser')).toHaveCount(0);
    const otherPage = await second.newPage();
    await otherPage.goto(baseURL + '/sign-in');
    await otherPage.getByLabel('Email address').fill(email);
    await otherPage.getByLabel('Password', { exact: true }).fill(password);
    await otherPage.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(otherPage).toHaveURL(/\/app\/library$/);
    await expect(otherPage.getByText('Persistent handbook', { exact: true }).first()).toBeVisible();
    await otherPage.reload();
    await expect(otherPage.getByText('Persistent handbook', { exact: true }).first()).toBeVisible();
    await otherPage.goto(baseURL + '/app/documents/' + id + '/edit');
    await expect(otherPage.getByLabel('Description', { exact: true })).toHaveValue('Remember these details');
    await otherPage.getByLabel('Title', { exact: true }).fill('Updated handbook');
    await otherPage.getByRole('button', { name: 'Save changes' }).click();
    await expect(otherPage).toHaveURL(baseURL + '/app/documents/' + id);
    await otherPage.reload();
    await expect(otherPage.getByRole('heading', { name: 'Updated handbook', exact: true })).toBeVisible();
    await expect(otherPage.getByRole('link', { name: 'CC BY 4.0', exact: true })).toBeVisible();
    await expect(otherPage.getByText('Author: Handbook collective', { exact: false })).toBeVisible();
    const stored = await otherPage.evaluate(() => localStorage.getItem('framashare-prototype-v1'));
    expect(stored).toBeNull();
    await page.goto(baseURL + '/app/settings/security');
    await page.getByRole('button', { name: 'Sign out', exact: true }).click();
    await expect(page).toHaveURL(/\/sign-in$/);
    expect((await author.request.get(baseURL + '/api/files/' + id)).status()).toBe(401);
    expect((await second.request.get(baseURL + '/api/files/' + id)).status()).toBe(200);
    const deletion = await second.request.delete(baseURL + '/api/files/' + id, { headers: { origin: new URL(baseURL!).origin } });
    expect(deletion.status()).toBe(204);
    expect((await second.request.get(baseURL + '/api/files/' + id)).status()).toBe(404);
  } finally { await author.close(); await second.close(); await guest.close(); }
});
