import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://localhost:5173';let checks=0;
async function go(path){await page.goto(base+path);await page.locator('h1').first().waitFor();await page.waitForTimeout(100);checks++;if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Overflow '+path+' '+await page.evaluate(()=>innerWidth));}
for(const width of [1440,390,320,768,1024]){await page.setViewportSize({width,height:1000});for(const path of ['/','/sign-in','/sign-up','/forgot-password','/reset-password','/help','/help/anonymous-publishing','/how-it-works','/about','/privacy','/terms'])await go(path);if(width===1440||width===390){await go('/');await page.screenshot({path:`docs/verification/screenshots/landing-${width===1440?'desktop':'mobile'}.png`,fullPage:true});await go('/sign-in');await page.screenshot({path:`docs/verification/screenshots/login-${width===1440?'desktop':'mobile'}.png`,fullPage:true});await go('/help');await page.screenshot({path:`docs/verification/screenshots/help-${width===1440?'desktop':'mobile'}.png`,fullPage:true});}}
await page.setViewportSize({width:1440,height:1000});await go('/sign-in?return=/app/settings/profile');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByText('Enter a valid email address.')).toBeVisible();await page.getByLabel('Email address',{exact:true}).fill('alex@example.com');await page.getByLabel('Password',{exact:true}).fill('readingroom');await page.getByRole('button',{name:'Show password'}).click();await expect(page.getByLabel('Password',{exact:true})).toHaveAttribute('type','text');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/app/settings/profile');await page.getByLabel('Name',{exact:true}).fill('Alex Reader');await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByRole('status')).toHaveText('Profile saved');
for(const width of [1440,390,320,768,1024]){await page.setViewportSize({width,height:1000});for(const section of ['profile','security','storage']){await go('/app/settings/'+section);if(width===1440||width===390)await page.screenshot({path:`docs/verification/screenshots/settings-${section}-${width===1440?'desktop':'mobile'}.png`,fullPage:true});}}
await go('/app/settings/security');await page.getByRole('button',{name:'Delete account',exact:true}).first().click();await expect(page.getByRole('dialog')).toBeVisible();await page.screenshot({path:'docs/verification/screenshots/delete-account-mobile.png',fullPage:true});await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByLabel('Current password').fill('readingroom');await page.getByLabel('New password',{exact:true}).fill('newpassword');await page.getByLabel('Confirm new password').fill('newpassword');await page.getByRole('button',{name:'Change password'}).click();await expect(page.getByRole('status')).toHaveText('Password change simulated');
await go('/forgot-password');await page.getByLabel('Email address').fill('alex@example.com');await page.getByRole('button',{name:'Send reset link'}).click();await expect(page.getByRole('heading',{name:'Check your inbox'})).toBeVisible();await page.getByRole('link',{name:'Open demo reset link'}).click();await page.getByLabel('New password',{exact:true}).fill('newpassword');await page.getByLabel('Confirm new password').fill('newpassword');await page.getByRole('button',{name:'Save new password'}).click();await expect(page.getByRole('heading',{name:'You’re all set'})).toBeVisible();
await go('/help');await page.getByRole('searchbox').fill('anonymous');await expect(page.locator('.help-card')).toHaveCount(2);await page.getByRole('searchbox').fill('zzzz');await expect(page.getByRole('heading',{name:'No articles found'})).toBeVisible();await page.getByRole('button',{name:'Clear search'}).click();await expect(page.locator('.help-card')).toHaveCount(6);
await go('/app/settings/security');await page.getByRole('button',{name:'Delete account',exact:true}).first().click();await page.getByLabel('Type DELETE to confirm').fill('DELETE');await page.getByRole('button',{name:'Delete account',exact:true}).last().click();await page.waitForURL(base+'/');await page.goto(base+'/share/workshop');await expect(page.getByText('Publication deleted',{exact:true})).toBeVisible();await go('/sign-up?return=/app/settings/storage');await page.getByLabel('Your name').fill('New Reader');await page.getByLabel('Email address',{exact:true}).fill('newreader@example.com');await page.getByLabel('Password',{exact:true}).fill('newpassword');await page.getByRole('button',{name:'Create account'}).click();await page.waitForURL('**/app/settings/storage');await expect(page.getByText('Your library has room to grow.')).toBeVisible();
console.log(JSON.stringify({navigationChecks:checks,errors,flows:['validation','password visibility','sign-in return','profile save','password change','delete dialog Escape','forgot/reset','help search'],screenshots:16}));await browser.close();
