<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ArrowLeft, ShieldCheck, Search, ExternalLink, Trash2 } from 'lucide-vue-next';
import UiModal from '../components/UiModal.vue';
import { state, deleteDocument, notify, delay, formatSize, formatDate, usage, type Publication } from '../services/store';
const route=useRoute(), router=useRouter();
const section=computed(()=>String(route.params.section));
const filter=ref('open'), search=ref(''), type=ref('all'), status=ref('all');
const busy=ref(false),error=ref(''), quota=ref(0),remove=ref<Publication|null>(null);
const settings=reactive({...state.settings,retention:[...state.settings.retention]});
const account=computed(()=>state.accounts.find(a=>a.id===route.params.id));
const report=computed(()=>state.reports.find(r=>r.id===route.params.id));
const publication=computed(()=>state.documents.find(d=>d.id===report.value?.documentId));
const reports=computed(()=>state.reports.filter(r=>r.status===filter.value));
const publications=computed(()=>state.documents.filter(d=>(type.value==='all'||d.format===type.value)&&(status.value==='all'||d.status===status.value)&&d.title.toLowerCase().includes(search.value.toLowerCase())));
const accounts=computed(()=>state.accounts.filter(a=>(a.name+' '+a.email).toLowerCase().includes(search.value.toLowerCase())));
const accountDocuments=computed(()=>state.documents.filter(d=>d.ownerId===account.value?.id&&!['deleted','removed'].includes(d.status)));
watch(account,a=>{quota.value=a?Math.round(a.quota/1000000):0},{immediate:true});
watch(()=>route.fullPath,()=>{error.value='';search.value='';remove.value=null});
function owner(id:string|null){return state.accounts.find(a=>a.id===id)?.name||'Anonymous'}
function active(d:Publication){return !['deleted','removed'].includes(d.status)&&(!d.deleteAt||d.deleteAt>state.now)}
async function operation(action:()=>void,message:string){error.value='';busy.value=true;try{await delay();action();notify(message)}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function dismiss(){await operation(()=>{if(report.value){report.value.status='resolved';report.value.decision='Dismissed'}},'Report dismissed')}
async function confirmRemoval(){const d=remove.value;if(!d)return;await operation(()=>{deleteDocument(d.id,true);remove.value=null},'Publication removed')}
async function saveQuota(){if(!Number.isInteger(Number(quota.value))||Number(quota.value)<1){error.value='Storage limit must be a positive whole number of MB.';return}await operation(()=>{if(account.value)account.value.quota=Number(quota.value)*1000000},'Account storage limit saved')}
async function saveSettings(){const values=[settings.fileMB,settings.albumMB,settings.albumCount,settings.quotaMB];if(values.some(n=>!Number.isInteger(Number(n))||Number(n)<1)){error.value='File sizes, image count and account storage must be positive whole numbers.';return}if(!settings.retention.length){error.value='Allow at least one anonymous retention period.';return}if(!settings.retention.includes(Number(settings.defaultRetention))){error.value='Choose a default from the allowed retention periods.';return}await operation(()=>{state.settings={fileMB:Number(settings.fileMB),albumMB:Number(settings.albumMB),albumCount:Number(settings.albumCount),quotaMB:Number(settings.quotaMB),retention:[...settings.retention].sort((a,b)=>a-b),defaultRetention:Number(settings.defaultRetention)}},'Instance settings saved')}
function preview(d:Publication){router.push({path:`/app/documents/${d.id}/read`,query:{return:route.fullPath,moderation:'true'}})}
</script>
<template>
<main class="page admin-page">
  <header class="page-heading"><div class="row muted small"><ShieldCheck :size="18"/>Administration</div><h1>{{ section==='reports'?'Reports':section==='publications'?'Publications':section==='accounts'?'Accounts':'Instance settings' }}</h1><p class="muted">Review reader reports, manage publications and set storage limits.</p></header>
  <nav class="tabs" aria-label="Administration"><RouterLink v-for="item in ['reports','publications','accounts','settings']" :key="item" :to="'/admin/'+item" :class="{active:section===item}">{{ item==='settings'?'Instance settings':item[0]?.toUpperCase()+item.slice(1) }}</RouterLink></nav>
  <p v-if="error" class="alert error" role="alert">{{error}}</p>
  <template v-if="section==='reports'">
    <template v-if="route.params.id">
      <RouterLink class="back row small" to="/admin/reports"><ArrowLeft :size="16"/>Back to reports</RouterLink>
      <div v-if="report" class="two-columns">
        <section class="card stack"><div class="row between wrap"><h2>Report details</h2><span class="badge" :class="report.status==='open'?'processing':'ready'">{{report.status==='open'?'Open':'Resolved'}}</span></div><dl class="details"><dt>Reason</dt><dd>{{report.reason}}</dd><dt>Submitted</dt><dd>{{formatDate(report.createdAt)}}</dd></dl><div><h3>Description</h3><p class="report-description">{{report.description}}</p></div><div v-if="report.decision" class="alert">{{report.decision}}</div><div v-if="report.status==='open'" class="row wrap"><button class="button secondary" :disabled="busy" @click="dismiss">{{busy?'Saving…':'Dismiss report'}}</button><button v-if="publication&&active(publication)" class="button danger" :disabled="busy" @click="remove=publication">Remove publication</button></div></section>
        <section v-if="publication" class="card stack"><h2>Publication for review</h2><h3 class="long-title">{{publication.title}}</h3><p>{{publication.description}}</p><dl class="details"><dt>Format</dt><dd>{{publication.format.toUpperCase()}}</dd><dt>Owner</dt><dd>{{owner(publication.ownerId)}}</dd><dt>Size</dt><dd>{{formatSize(publication.size)}}</dd><dt>Status</dt><dd><span class="badge" :class="publication.status">{{publication.status}}</span></dd><dt>Retention</dt><dd>{{publication.deleteAt?'Scheduled deletion: '+formatDate(publication.deleteAt):'Stored in an account'}}</dd></dl><p class="muted small">Moderation preview does not use a recipient reading session.</p><button v-if="active(publication)" class="button secondary" @click="preview(publication)"><ExternalLink :size="16"/>Open controlled preview</button></section>
      </div><div v-else class="card empty"><h2>Report unavailable</h2><p>This report could not be found.</p></div>
    </template>
    <template v-else>
      <div class="row between wrap list-toolbar"><div class="segmented" aria-label="Report status"><button v-for="item in ['open','resolved']" :key="item" :class="{active:filter===item}" :aria-pressed="filter===item" @click="filter=item">{{item==='open'?'Open':'Resolved'}} ({{state.reports.filter(r=>r.status===item).length}})</button></div><span class="small muted">{{reports.length}} {{reports.length===1?'report':'reports'}}</span></div>
      <div class="card table-card"><table v-if="reports.length" class="table"><thead><tr><th>Reason</th><th>Publication</th><th>Submitted</th><th>Status</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody><tr v-for="r in reports" :key="r.id"><td><RouterLink :to="'/admin/reports/'+r.id" class="report-link">{{r.reason}}</RouterLink><p class="small muted report-excerpt">{{r.description}}</p></td><td class="long-title">{{state.documents.find(d=>d.id===r.documentId)?.title||'Unavailable publication'}}</td><td class="small">{{formatDate(r.createdAt)}}</td><td><span class="badge" :class="r.status==='open'?'processing':'ready'">{{r.status}}</span></td><td><RouterLink class="button secondary" :to="'/admin/reports/'+r.id">Review report</RouterLink></td></tr></tbody></table><div v-else class="empty"><h2>No {{filter}} reports</h2><p class="muted">Reports submitted by readers appear here.</p></div></div>
    </template>
  </template>
  <template v-else-if="section==='publications'">
    <div class="filters"><label class="field search"><span>Search publications</span><div class="search-wrap"><Search :size="18"/><input v-model="search" placeholder="Search by title"/></div></label><label class="field">Format<select v-model="type"><option value="all">All formats</option><option value="pdf">PDF</option><option value="epub">EPUB</option><option value="album">Album</option></select></label><label class="field">Status<select v-model="status"><option value="all">All statuses</option><option v-for="s in ['ready','processing','failed','deleted','removed']" :key="s" :value="s">{{s[0]?.toUpperCase()+s.slice(1)}}</option></select></label></div>
    <div class="card table-card"><table v-if="publications.length" class="table"><thead><tr><th>Publication</th><th>Owner</th><th>Retention</th><th>Status</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody><tr v-for="d in publications" :key="d.id"><td><strong class="long-title">{{d.title}}</strong><p class="small muted">{{d.format.toUpperCase()}} · {{formatSize(d.size)}}</p></td><td>{{owner(d.ownerId)}}</td><td class="small">{{d.deleteAt?formatDate(d.deleteAt):'Account storage'}}</td><td><span class="badge" :class="d.status">{{d.deleteAt&&d.deleteAt<=state.now?'Expired':d.status}}</span></td><td><div class="row wrap"><button v-if="active(d)" class="button secondary" @click="preview(d)">Preview</button><button v-if="active(d)" class="icon-button" :aria-label="'Remove '+d.title" @click="remove=d"><Trash2 :size="18"/></button></div></td></tr></tbody></table><div v-else class="empty"><h2>No matching publications</h2><p class="muted">Try a different title, format or status.</p><button class="button secondary" @click="search='';type='all';status='all'">Clear filters</button></div></div>
  </template>
  <template v-else-if="section==='accounts'">
    <template v-if="route.params.id"><RouterLink class="back row small" to="/admin/accounts"><ArrowLeft :size="16"/>Back to accounts</RouterLink><div v-if="account" class="two-columns"><section class="card stack"><div class="row"><span class="avatar">{{account.name.split(' ').map(n=>n[0]).join('').slice(0,2)}}</span><div><h2 class="account-name">{{account.name}}</h2><p class="small muted">{{account.email}}</p></div></div><dl class="details"><dt>Role</dt><dd>{{account.role==='admin'?'Administrator':'Author'}}</dd><dt>Publications</dt><dd>{{accountDocuments.length}}</dd><dt>Storage used</dt><dd>{{formatSize(usage(account.id))}} of {{formatSize(account.quota)}}</dd></dl><progress :value="Math.min(usage(account.id),account.quota)" :max="account.quota" aria-label="Account storage used"/><p v-if="usage(account.id)>account.quota" class="alert error">This account is above its limit. New uploads are blocked until space is freed.</p><form class="stack" @submit.prevent="saveQuota"><label class="field">Storage limit (MB)<input v-model.number="quota" type="number" min="1" step="1" required :disabled="busy"/><small>Lowering the limit keeps existing publications and blocks new uploads when storage is full.</small></label><button class="button" :disabled="busy">{{busy?'Saving…':'Save storage limit'}}</button></form></section><section class="card"><h2>Account publications</h2><ul class="publication-list"><li v-for="d in accountDocuments" :key="d.id"><span class="long-title">{{d.title}}</span><span class="small muted">{{formatSize(d.size)}}</span></li></ul><p v-if="!accountDocuments.length" class="muted">This account has no publications.</p></section></div><div v-else class="card empty"><h2>Account unavailable</h2><p>This account could not be found.</p></div></template>
    <template v-else><label class="field list-toolbar account-search">Search accounts<input v-model="search" placeholder="Name or email"/></label><div class="card table-card"><table v-if="accounts.length" class="table"><thead><tr><th>Account</th><th>Role</th><th>Storage</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody><tr v-for="a in accounts" :key="a.id"><td><strong>{{a.name}}</strong><p class="small muted">{{a.email}}</p></td><td>{{a.role==='admin'?'Administrator':'Author'}}</td><td>{{formatSize(usage(a.id))}} / {{formatSize(a.quota)}}<p v-if="usage(a.id)>a.quota" class="small error">Over storage limit</p></td><td><RouterLink class="button secondary" :to="'/admin/accounts/'+a.id">View account</RouterLink></td></tr></tbody></table><div v-else class="empty"><h2>No matching accounts</h2><button class="button secondary" @click="search=''">Clear search</button></div></div></template>
  </template>
  <template v-else-if="section==='settings'">
    <form class="settings-form stack" @submit.prevent="saveSettings"><section class="card stack"><h2>Publication limits</h2><div class="two-columns"><label class="field">Maximum PDF or EPUB size (MB)<input v-model.number="settings.fileMB" type="number" min="1" step="1" required/></label><label class="field">Maximum album size (MB)<input v-model.number="settings.albumMB" type="number" min="1" step="1" required/></label><label class="field">Maximum images in an album<input v-model.number="settings.albumCount" type="number" min="1" step="1" required/></label><label class="field">Storage for new accounts (MB)<input v-model.number="settings.quotaMB" type="number" min="1" step="1" required/><small>Existing account limits are edited individually in Accounts.</small></label></div></section><section class="card stack"><h2>Anonymous retention</h2><fieldset><legend>Allowed retention periods</legend><div class="row wrap"><label v-for="days in [1,7,30]" :key="days" class="checkbox"><input v-model="settings.retention" type="checkbox" :value="days"/>{{days}} {{days===1?'day':'days'}}</label></div></fieldset><label class="field">Default retention<select v-model.number="settings.defaultRetention"><option v-for="days in settings.retention" :key="days" :value="days">{{days}} {{days===1?'day':'days'}}</option></select></label><p class="alert">Retention changes apply to new uploads. Existing publication deletion dates stay the same.</p></section><div class="row wrap"><button class="button" :disabled="busy">{{busy?'Saving…':'Save instance settings'}}</button><button class="button secondary" type="button" :disabled="busy" @click="Object.assign(settings,{...state.settings,retention:[...state.settings.retention]});error=''">Discard changes</button></div></form>
  </template>
  <section v-else class="card empty"><h2>Page unavailable</h2><RouterLink class="button" to="/admin/reports">View reports</RouterLink></section>
  <UiModal v-if="remove" title="Remove publication?" @close="!busy&&(remove=null)"><p><strong>{{remove.title}}</strong> will be removed from the collection.</p><p>All its sharing links will stop working, including active reading sessions. Open reports about this publication will be resolved. This cannot be undone.</p><p v-if="error" class="alert error" role="alert">{{error}}</p><div class="actions"><button class="button secondary" :disabled="busy" @click="remove=null">Cancel</button><button class="button danger" :disabled="busy" @click="confirmRemoval">{{busy?'Removing…':'Remove publication'}}</button></div></UiModal>
</main>
</template>
<style scoped>
.admin-page{max-width:1280px}.page-heading h1{margin-top:12px;margin-bottom:12px}.list-toolbar{margin-bottom:24px}.filters{display:grid;grid-template-columns:minmax(180px,1fr) 180px 180px;gap:16px;margin-bottom:24px}.search-wrap{position:relative}.search-wrap svg{position:absolute;left:14px;top:14px;color:var(--secondary)}.search-wrap input{padding-left:42px}.table-card{padding:8px 12px}.table th{white-space:nowrap}.table td{vertical-align:middle}.table td:first-child{max-width:350px}.table td p{margin:8px 0 0}.long-title{overflow-wrap:anywhere;line-height:1.5;font-weight:500}.report-link{font-weight:500;text-decoration:underline;text-underline-offset:3px}.report-excerpt{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.report-description{white-space:pre-wrap;overflow-wrap:anywhere}.back{margin-bottom:24px;min-height:44px;display:inline-flex}.details{display:grid;grid-template-columns:100px 1fr;gap:14px;margin:0;font-size:14px}.details dt{color:var(--secondary)}.details dd{margin:0;overflow-wrap:anywhere}.stack h2,.stack h3,.stack p{margin-bottom:0}.stack .row h2{margin:0}.account-search{max-width:400px}.avatar{display:grid;place-items:center;width:56px;height:56px;background:#e6ece4;border-radius:50%;flex-shrink:0}.account-name{margin-bottom:4px!important}.publication-list{padding:0;list-style:none}.publication-list li{display:flex;justify-content:space-between;gap:20px;padding:16px 0;border-bottom:1px solid var(--border)}.publication-list li .muted{flex-shrink:0}.settings-form{max-width:820px}fieldset{border:0;padding:0;margin:0}legend{font-size:14px;font-weight:500;margin-bottom:8px}fieldset .checkbox{margin-right:20px}.settings-form .alert{margin:0}.icon-button{display:inline-flex;align-items:center;justify-content:center}@media(max-width:800px){.filters{grid-template-columns:1fr 1fr}.filters .search{grid-column:1/-1}.table-card{padding:8px 16px}.table td:first-child{max-width:none}.table td p{margin:6px 0}.table td{padding:7px 0}.table td:last-child{padding-top:12px}.table td .button{min-width:120px}.table tr:last-child{border-bottom:0}.table tr{padding:20px 0}.table .small{line-height:1.5}}@media(max-width:400px){.filters{grid-template-columns:1fr}.filters .search{grid-column:auto}.segmented button{padding:8px 10px}.details{grid-template-columns:85px 1fr}.tabs a{padding:14px 10px}.publication-list li{flex-wrap:wrap;gap:8px}}
</style>
